export const CLIENT_ENV = {
  CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
  CLERK_FALLBACK_REDIRECT_URL:
    process.env.NEXT_PUBLIC_CLERK_FALLBACK_REDIRECT_URL,
};

if (!CLIENT_ENV.CLERK_PUBLISHABLE_KEY) {
  console.warn('⚠️ Missing CLERK_PUBLISHABLE_KEY');
}

if (!CLIENT_ENV.CLERK_FALLBACK_REDIRECT_URL) {
  console.warn('⚠️ Missing CLERK_FALLBACK_REDIRECT_URL');
}
